spring.application.name=demo
server.servlet.context-path=/path-lab

# Database Configuration
spring.datasource.url=jdbc:h2:mem:pathlabdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging levels
logging.level.root=INFO
logging.level.com.lab.demo.Controller=INFO
logging.level.com.lab.demo.config=INFO
